---
before_script:
  - apk add --update --no-cache python3 py3-pip
  - /usr/bin/pip3 install -r requirements.txt

test:
  stage: test
  script:
    - mkdocs build --script --verbose --site-dir test
  artifacts:
    paths:
      - test
  except:
    - main

pages:
  stage: deploy
  script:
    - mkdocs build --verbose
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main
...
